---
type: yml
#this is just example config not use it on production

application:
  graceful_shutdown_timeout: 10

http_server:
  port: 8088

broker:
  username: user
  password: password
  host: localhost
  port: 5672



mysql:
  port: 3306
  host: localhost
  db_name: discount_db
  username: testuser
  password: veryhardhardpasswordformysql

redis:
  port: 6379
  host: localhost
  db: 0
  password: ""
